# Generated by Django 5.0.7 on 2024-09-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phonebook',
            new_name='Person',
        ),
    ]
